BASE_URL = "http://localhost/"
REGISTRATION_URL = f"{BASE_URL}index.php?route=account/register"
LOGIN_URL = f"{BASE_URL}/index.php?route=account/login"
MY_ACCOUNT_URL = f"{BASE_URL}index.php?route=account/account"
CONTACT_FORM_URL = f"{BASE_URL}index.php?route=information/contact"
UNIQUE_ITEM_URL = f"{BASE_URL}index.php?route=product/product"
PRODUCT_CATEGORY_URL = f"{BASE_URL}index.php?route=product/category&language=en-gb&path=20"